const value = {
  "location": {
    "name": "Delhi",
    "region": "Delhi",
    "country": "India",
    "lat": 28.67,
    "lon": 77.22,
    "tz_id": "Asia/Kolkata",
    "localtime_epoch": 1671368663,
    "localtime": "2022-12-18 18:34"
  },
  "current": {
    "last_updated_epoch": 1671368400,
    "last_updated": "2022-12-18 18:30",
    "temp_c": 18.0,
    "temp_f": 64.4,
    "is_day": 0,
    "condition": {
      "text": "Overcast",
      "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
      "code": 1009
    },
    "wind_mph": 2.2,
    "wind_kph": 3.6,
    "wind_degree": 10,
    "wind_dir": "NW",
    "pressure_mb": 1014.0,
    "pressure_in": 29.94,
    "precip_mm": 0.0,
    "precip_in": 0.0,
    "humidity": 60,
    "cloud": 0,
    "feelslike_c": 18.0,
    "feelslike_f": 64.4,
    "vis_km": 2.1,
    "vis_miles": 1.0,
    "uv": 1.0,
    "gust_mph": 3.8,
    "gust_kph": 6.1,
    "air_quality": {
      "co": 1895.9000244140625,
      "no2": 63.79999923706055,
      "o3": 12.5,
      "so2": 28.399999618530273,
      "pm2_5": 206.6999969482422,
      "pm10": 257.1000061035156,
      "us-epa-index": 5,
      "gb-defra-index": 10
    }
  },
  "forecast": {
    "forecastday": [
      {
        "date": "2022-12-18",
        "date_epoch": 1671321600,
        "day": {
          "maxtemp_c": 26.8,
          "maxtemp_f": 80.2,
          "mintemp_c": 14.5,
          "mintemp_f": 58.1,
          "avgtemp_c": 19.7,
          "avgtemp_f": 67.4,
          "maxwind_mph": 3.6,
          "maxwind_kph": 5.8,
          "totalprecip_mm": 0.0,
          "totalprecip_in": 0.0,
          "totalsnow_cm": 0.0,
          "avgvis_km": 10.0,
          "avgvis_miles": 6.0,
          "avghumidity": 22.0,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
          },
          "uv": 5.0
        },
        "astro": {
          "sunrise": "07:09 AM",
          "sunset": "05:28 PM",
          "moonrise": "01:34 AM",
          "moonset": "01:35 PM",
          "moon_phase": "Waning Crescent",
          "moon_illumination": "26"
        },
        "hour": [
          {
            "time_epoch": 1671301800,
            "time": "2022-12-18 00:00",
            "temp_c": 16.7,
            "temp_f": 62.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 1.6,
            "wind_kph": 2.5,
            "wind_degree": 340,
            "wind_dir": "NNW",
            "pressure_mb": 1015.0,
            "pressure_in": 29.98,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 25,
            "cloud": 0,
            "feelslike_c": 16.7,
            "feelslike_f": 62.1,
            "windchill_c": 16.7,
            "windchill_f": 62.1,
            "heatindex_c": 16.7,
            "heatindex_f": 62.1,
            "dewpoint_c": -3.5,
            "dewpoint_f": 25.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 3.1,
            "gust_kph": 5.0,
            "uv": 1.0
          },
          {
            "time_epoch": 1671305400,
            "time": "2022-12-18 01:00",
            "temp_c": 16.3,
            "temp_f": 61.3,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 2.0,
            "wind_kph": 3.2,
            "wind_degree": 337,
            "wind_dir": "NNW",
            "pressure_mb": 1016.0,
            "pressure_in": 29.99,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 25,
            "cloud": 0,
            "feelslike_c": 16.3,
            "feelslike_f": 61.3,
            "windchill_c": 16.3,
            "windchill_f": 61.3,
            "heatindex_c": 16.3,
            "heatindex_f": 61.3,
            "dewpoint_c": -3.6,
            "dewpoint_f": 25.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 4.0,
            "gust_kph": 6.5,
            "uv": 1.0
          },
          {
            "time_epoch": 1671309000,
            "time": "2022-12-18 02:00",
            "temp_c": 15.8,
            "temp_f": 60.4,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 1.8,
            "wind_kph": 2.9,
            "wind_degree": 358,
            "wind_dir": "N",
            "pressure_mb": 1016.0,
            "pressure_in": 29.99,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 25,
            "cloud": 0,
            "feelslike_c": 15.8,
            "feelslike_f": 60.4,
            "windchill_c": 15.8,
            "windchill_f": 60.4,
            "heatindex_c": 15.8,
            "heatindex_f": 60.4,
            "dewpoint_c": -3.9,
            "dewpoint_f": 25.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 3.6,
            "gust_kph": 5.8,
            "uv": 1.0
          },
          {
            "time_epoch": 1671312600,
            "time": "2022-12-18 03:00",
            "temp_c": 15.4,
            "temp_f": 59.7,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 2.0,
            "wind_kph": 3.2,
            "wind_degree": 8,
            "wind_dir": "N",
            "pressure_mb": 1016.0,
            "pressure_in": 29.99,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 26,
            "cloud": 0,
            "feelslike_c": 15.4,
            "feelslike_f": 59.7,
            "windchill_c": 15.4,
            "windchill_f": 59.7,
            "heatindex_c": 15.4,
            "heatindex_f": 59.7,
            "dewpoint_c": -4.0,
            "dewpoint_f": 24.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 4.0,
            "gust_kph": 6.5,
            "uv": 1.0
          },
          {
            "time_epoch": 1671316200,
            "time": "2022-12-18 04:00",
            "temp_c": 15.0,
            "temp_f": 59.0,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 1.6,
            "wind_kph": 2.5,
            "wind_degree": 8,
            "wind_dir": "N",
            "pressure_mb": 1016.0,
            "pressure_in": 29.99,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 27,
            "cloud": 0,
            "feelslike_c": 15.0,
            "feelslike_f": 59.0,
            "windchill_c": 15.0,
            "windchill_f": 59.0,
            "heatindex_c": 15.0,
            "heatindex_f": 59.0,
            "dewpoint_c": -4.0,
            "dewpoint_f": 24.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 3.1,
            "gust_kph": 5.0,
            "uv": 1.0
          },
          {
            "time_epoch": 1671319800,
            "time": "2022-12-18 05:00",
            "temp_c": 14.7,
            "temp_f": 58.5,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 1.1,
            "wind_kph": 1.8,
            "wind_degree": 351,
            "wind_dir": "N",
            "pressure_mb": 1016.0,
            "pressure_in": 29.99,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 27,
            "cloud": 0,
            "feelslike_c": 14.7,
            "feelslike_f": 58.5,
            "windchill_c": 14.7,
            "windchill_f": 58.5,
            "heatindex_c": 14.7,
            "heatindex_f": 58.5,
            "dewpoint_c": -4.1,
            "dewpoint_f": 24.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 2.2,
            "gust_kph": 3.6,
            "uv": 1.0
          },
          {
            "time_epoch": 1671323400,
            "time": "2022-12-18 06:00",
            "temp_c": 14.5,
            "temp_f": 58.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 1.1,
            "wind_kph": 1.8,
            "wind_degree": 341,
            "wind_dir": "NNW",
            "pressure_mb": 1016.0,
            "pressure_in": 30.01,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 27,
            "cloud": 0,
            "feelslike_c": 14.5,
            "feelslike_f": 58.1,
            "windchill_c": 14.5,
            "windchill_f": 58.1,
            "heatindex_c": 14.5,
            "heatindex_f": 58.1,
            "dewpoint_c": -4.1,
            "dewpoint_f": 24.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 2.2,
            "gust_kph": 3.6,
            "uv": 1.0
          },
          {
            "time_epoch": 1671327000,
            "time": "2022-12-18 07:00",
            "temp_c": 14.5,
            "temp_f": 58.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 1.3,
            "wind_kph": 2.2,
            "wind_degree": 334,
            "wind_dir": "NNW",
            "pressure_mb": 1017.0,
            "pressure_in": 30.02,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 28,
            "cloud": 0,
            "feelslike_c": 14.5,
            "feelslike_f": 58.1,
            "windchill_c": 14.5,
            "windchill_f": 58.1,
            "heatindex_c": 14.5,
            "heatindex_f": 58.1,
            "dewpoint_c": -3.9,
            "dewpoint_f": 25.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 2.7,
            "gust_kph": 4.3,
            "uv": 4.0
          },
          {
            "time_epoch": 1671330600,
            "time": "2022-12-18 08:00",
            "temp_c": 15.7,
            "temp_f": 60.3,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.2,
            "wind_kph": 3.6,
            "wind_degree": 1,
            "wind_dir": "N",
            "pressure_mb": 1018.0,
            "pressure_in": 30.05,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 26,
            "cloud": 0,
            "feelslike_c": 15.7,
            "feelslike_f": 60.3,
            "windchill_c": 15.7,
            "windchill_f": 60.3,
            "heatindex_c": 15.7,
            "heatindex_f": 60.3,
            "dewpoint_c": -3.5,
            "dewpoint_f": 25.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 3.6,
            "gust_kph": 5.8,
            "uv": 5.0
          },
          {
            "time_epoch": 1671334200,
            "time": "2022-12-18 09:00",
            "temp_c": 17.6,
            "temp_f": 63.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 1.3,
            "wind_kph": 2.2,
            "wind_degree": 11,
            "wind_dir": "NNE",
            "pressure_mb": 1018.0,
            "pressure_in": 30.07,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 23,
            "cloud": 0,
            "feelslike_c": 17.6,
            "feelslike_f": 63.7,
            "windchill_c": 17.6,
            "windchill_f": 63.7,
            "heatindex_c": 17.6,
            "heatindex_f": 63.7,
            "dewpoint_c": -3.5,
            "dewpoint_f": 25.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 1.8,
            "gust_kph": 2.9,
            "uv": 5.0
          },
          {
            "time_epoch": 1671337800,
            "time": "2022-12-18 10:00",
            "temp_c": 19.4,
            "temp_f": 66.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 1.3,
            "wind_kph": 2.2,
            "wind_degree": 8,
            "wind_dir": "N",
            "pressure_mb": 1018.0,
            "pressure_in": 30.07,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 21,
            "cloud": 0,
            "feelslike_c": 19.4,
            "feelslike_f": 66.9,
            "windchill_c": 19.4,
            "windchill_f": 66.9,
            "heatindex_c": 19.4,
            "heatindex_f": 66.9,
            "dewpoint_c": -3.5,
            "dewpoint_f": 25.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 1.6,
            "gust_kph": 2.5,
            "uv": 5.0
          },
          {
            "time_epoch": 1671341400,
            "time": "2022-12-18 11:00",
            "temp_c": 24.0,
            "temp_f": 75.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 1.6,
            "wind_kph": 2.5,
            "wind_degree": 347,
            "wind_dir": "NNW",
            "pressure_mb": 1018.0,
            "pressure_in": 30.05,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 19,
            "cloud": 0,
            "feelslike_c": 23.2,
            "feelslike_f": 73.8,
            "windchill_c": 24.0,
            "windchill_f": 75.2,
            "heatindex_c": 23.2,
            "heatindex_f": 73.8,
            "dewpoint_c": -1.1,
            "dewpoint_f": 30.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 1.8,
            "gust_kph": 2.9,
            "uv": 6.0
          },
          {
            "time_epoch": 1671345000,
            "time": "2022-12-18 12:00",
            "temp_c": 25.2,
            "temp_f": 77.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.5,
            "wind_kph": 4.0,
            "wind_degree": 335,
            "wind_dir": "NNW",
            "pressure_mb": 1016.0,
            "pressure_in": 30.01,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 17,
            "cloud": 0,
            "feelslike_c": 23.9,
            "feelslike_f": 75.0,
            "windchill_c": 25.2,
            "windchill_f": 77.4,
            "heatindex_c": 23.9,
            "heatindex_f": 75.0,
            "dewpoint_c": -1.3,
            "dewpoint_f": 29.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 2.9,
            "gust_kph": 4.7,
            "uv": 7.0
          },
          {
            "time_epoch": 1671348600,
            "time": "2022-12-18 13:00",
            "temp_c": 26.1,
            "temp_f": 79.0,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.7,
            "wind_kph": 4.3,
            "wind_degree": 327,
            "wind_dir": "NNW",
            "pressure_mb": 1015.0,
            "pressure_in": 29.98,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 16,
            "cloud": 0,
            "feelslike_c": 24.5,
            "feelslike_f": 76.1,
            "windchill_c": 26.1,
            "windchill_f": 79.0,
            "heatindex_c": 24.5,
            "heatindex_f": 76.1,
            "dewpoint_c": -1.5,
            "dewpoint_f": 29.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 3.1,
            "gust_kph": 5.0,
            "uv": 7.0
          },
          {
            "time_epoch": 1671352200,
            "time": "2022-12-18 14:00",
            "temp_c": 26.6,
            "temp_f": 79.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.9,
            "wind_kph": 4.7,
            "wind_degree": 327,
            "wind_dir": "NNW",
            "pressure_mb": 1014.0,
            "pressure_in": 29.95,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 16,
            "cloud": 0,
            "feelslike_c": 24.9,
            "feelslike_f": 76.8,
            "windchill_c": 26.6,
            "windchill_f": 79.9,
            "heatindex_c": 24.9,
            "heatindex_f": 76.8,
            "dewpoint_c": -1.6,
            "dewpoint_f": 29.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 3.4,
            "gust_kph": 5.4,
            "uv": 7.0
          },
          {
            "time_epoch": 1671355800,
            "time": "2022-12-18 15:00",
            "temp_c": 26.8,
            "temp_f": 80.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 328,
            "wind_dir": "NNW",
            "pressure_mb": 1014.0,
            "pressure_in": 29.94,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 16,
            "cloud": 0,
            "feelslike_c": 25.1,
            "feelslike_f": 77.2,
            "windchill_c": 26.8,
            "windchill_f": 80.2,
            "heatindex_c": 25.1,
            "heatindex_f": 77.2,
            "dewpoint_c": -1.4,
            "dewpoint_f": 29.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 4.0,
            "gust_kph": 6.5,
            "uv": 7.0
          },
          {
            "time_epoch": 1671359400,
            "time": "2022-12-18 16:00",
            "temp_c": 26.1,
            "temp_f": 79.0,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 321,
            "wind_dir": "NW",
            "pressure_mb": 1014.0,
            "pressure_in": 29.93,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 17,
            "cloud": 0,
            "feelslike_c": 24.5,
            "feelslike_f": 76.1,
            "windchill_c": 26.1,
            "windchill_f": 79.0,
            "heatindex_c": 24.5,
            "heatindex_f": 76.1,
            "dewpoint_c": -0.5,
            "dewpoint_f": 31.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 4.0,
            "gust_kph": 6.5,
            "uv": 7.0
          },
          {
            "time_epoch": 1671363000,
            "time": "2022-12-18 17:00",
            "temp_c": 24.0,
            "temp_f": 75.2,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5.0,
            "wind_degree": 332,
            "wind_dir": "NNW",
            "pressure_mb": 1014.0,
            "pressure_in": 29.93,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 19,
            "cloud": 0,
            "feelslike_c": 23.2,
            "feelslike_f": 73.8,
            "windchill_c": 24.0,
            "windchill_f": 75.2,
            "heatindex_c": 23.2,
            "heatindex_f": 73.8,
            "dewpoint_c": -0.8,
            "dewpoint_f": 30.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 3.6,
            "gust_kph": 5.8,
            "uv": 1.0
          },
          {
            "time_epoch": 1671366600,
            "time": "2022-12-18 18:00",
            "temp_c": 23.0,
            "temp_f": 73.4,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5.0,
            "wind_degree": 336,
            "wind_dir": "NNW",
            "pressure_mb": 1014.0,
            "pressure_in": 29.94,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 21,
            "cloud": 0,
            "feelslike_c": 22.7,
            "feelslike_f": 72.9,
            "windchill_c": 23.0,
            "windchill_f": 73.4,
            "heatindex_c": 22.7,
            "heatindex_f": 72.9,
            "dewpoint_c": -0.7,
            "dewpoint_f": 30.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 3.8,
            "gust_kph": 6.1,
            "uv": 1.0
          },
          {
            "time_epoch": 1671370200,
            "time": "2022-12-18 19:00",
            "temp_c": 22.3,
            "temp_f": 72.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 347,
            "wind_dir": "NNW",
            "pressure_mb": 1014.0,
            "pressure_in": 29.96,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 22,
            "cloud": 0,
            "feelslike_c": 22.5,
            "feelslike_f": 72.5,
            "windchill_c": 22.3,
            "windchill_f": 72.1,
            "heatindex_c": 22.5,
            "heatindex_f": 72.5,
            "dewpoint_c": -0.5,
            "dewpoint_f": 31.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 4.3,
            "gust_kph": 6.8,
            "uv": 1.0
          },
          {
            "time_epoch": 1671373800,
            "time": "2022-12-18 20:00",
            "temp_c": 18.8,
            "temp_f": 65.8,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 354,
            "wind_dir": "N",
            "pressure_mb": 1015.0,
            "pressure_in": 29.96,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 23,
            "cloud": 0,
            "feelslike_c": 18.8,
            "feelslike_f": 65.8,
            "windchill_c": 18.8,
            "windchill_f": 65.8,
            "heatindex_c": 18.8,
            "heatindex_f": 65.8,
            "dewpoint_c": -2.8,
            "dewpoint_f": 27.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 6.7,
            "gust_kph": 10.8,
            "uv": 1.0
          },
          {
            "time_epoch": 1671377400,
            "time": "2022-12-18 21:00",
            "temp_c": 18.3,
            "temp_f": 64.9,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 356,
            "wind_dir": "N",
            "pressure_mb": 1015.0,
            "pressure_in": 29.97,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 24,
            "cloud": 0,
            "feelslike_c": 18.3,
            "feelslike_f": 64.9,
            "windchill_c": 18.3,
            "windchill_f": 64.9,
            "heatindex_c": 18.3,
            "heatindex_f": 64.9,
            "dewpoint_c": -2.6,
            "dewpoint_f": 27.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 7.2,
            "gust_kph": 11.5,
            "uv": 1.0
          },
          {
            "time_epoch": 1671381000,
            "time": "2022-12-18 22:00",
            "temp_c": 17.8,
            "temp_f": 64.0,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5.0,
            "wind_degree": 357,
            "wind_dir": "N",
            "pressure_mb": 1015.0,
            "pressure_in": 29.96,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 25,
            "cloud": 0,
            "feelslike_c": 17.8,
            "feelslike_f": 64.0,
            "windchill_c": 17.8,
            "windchill_f": 64.0,
            "heatindex_c": 17.8,
            "heatindex_f": 64.0,
            "dewpoint_c": -2.6,
            "dewpoint_f": 27.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 6.3,
            "gust_kph": 10.1,
            "uv": 1.0
          },
          {
            "time_epoch": 1671384600,
            "time": "2022-12-18 23:00",
            "temp_c": 17.4,
            "temp_f": 63.3,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 2.9,
            "wind_kph": 4.7,
            "wind_degree": 348,
            "wind_dir": "NNW",
            "pressure_mb": 1014.0,
            "pressure_in": 29.96,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 25,
            "cloud": 0,
            "feelslike_c": 17.4,
            "feelslike_f": 63.3,
            "windchill_c": 17.4,
            "windchill_f": 63.3,
            "heatindex_c": 17.4,
            "heatindex_f": 63.3,
            "dewpoint_c": -2.5,
            "dewpoint_f": 27.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 5.8,
            "gust_kph": 9.4,
            "uv": 1.0
          }
        ]
      }
    ]
  }
}

export default value;